version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.11.1      
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
    restart: always  # This line has been added

volumes:
  esdata1:
    driver: local

networks:
  esnet:
    driver: bridge

