version: '3.3'
services:
  postgres:
    image: postgres:latest
    ports: 
      - 5434:5432
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root     
    volumes:
      - ./data:/var/lib/postgresql/data

