version: '3'
services:
  redis:
    restart: always
    image: redis:latest
    container_name: rediscache
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data    
volumes:
  redis-data:
